default:
    sr: 16000
    frame_shift: 0.005
    frame_length:  0.025
    win_length: 400
    hop_length: 80
    n_fft: 512
    preemphasis: 0.97
    n_mfcc: 40
    n_iter: 60 # Number of inversion iterations
    n_mels: 80
    duration: 2
    max_db: 35
    min_db: -55

    # model
    hidden_units: 256  # alias: E
    num_banks: 16
    num_highway_blocks: 4
    norm_type: 'ins'  # a normalizer function. value: bn, ln, ins, or None
    t: 1.0  # temperature
    dropout_rate: 0.2

    # train
    batch_size: 32

logdir_path: '/logdir'

train:
    # path
    data_path: 'datasets/guo/*.wav'
    p_path: 'datasets/wang/'

    # model
    hidden_units: 256  # alias: E
    num_banks: 8
    num_highway_blocks: 8
    norm_type: 'ins'  # a normalizer function. value: bn, ln, ins, or None
    t: 1.0  # temperature
    dropout_rate: 0.2

    # train
    batch_size: 32
    lr: 0.0003
    lr_cyclic_margin: 0.
    lr_cyclic_steps: 5000
    clip_value_max: 3.
    clip_value_min: -3.
    clip_norm: 10
    num_epochs: 10000
    steps_per_epoch: 100
    save_per_epoch: 50
    test_per_epoch: 1
    num_gpu: 1

test:
    # path
    data_path: 'datasets/guo/*.wav'
    p_path: 'datasets/wang/'

    # test
    batch_size: 32

convert:
    # path
    data_path: 'datasets/guo/*.wav'

    # convert
    one_full_wav: False
    batch_size: 1
    emphasis_magnitude: 1.2